/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibertacaoRouteImport } from './routes/libertacao'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuraRouteImport } from './routes/aura'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuraIndexRouteImport } from './routes/aura.index'
import { Route as AuraVestuarioRouteImport } from './routes/aura.vestuario'
import { Route as AuraSkincareRouteImport } from './routes/aura.skincare'
import { Route as AuraPerfumeRouteImport } from './routes/aura.perfume'
import { Route as AuraCuidadosRouteImport } from './routes/aura.cuidados'
import { Route as AuraCorpoRouteImport } from './routes/aura.corpo'
import { Route as AuraCabeloRouteImport } from './routes/aura.cabelo'
import { Route as AuraBarbaRouteImport } from './routes/aura.barba'
import { Route as AuraAcessoriosRouteImport } from './routes/aura.acessorios'

const LibertacaoRoute = LibertacaoRouteImport.update({
  id: '/libertacao',
  path: '/libertacao',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraRoute = AuraRouteImport.update({
  id: '/aura',
  path: '/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuraIndexRoute = AuraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuraRoute,
} as any)
const AuraVestuarioRoute = AuraVestuarioRouteImport.update({
  id: '/vestuario',
  path: '/vestuario',
  getParentRoute: () => AuraRoute,
} as any)
const AuraSkincareRoute = AuraSkincareRouteImport.update({
  id: '/skincare',
  path: '/skincare',
  getParentRoute: () => AuraRoute,
} as any)
const AuraPerfumeRoute = AuraPerfumeRouteImport.update({
  id: '/perfume',
  path: '/perfume',
  getParentRoute: () => AuraRoute,
} as any)
const AuraCuidadosRoute = AuraCuidadosRouteImport.update({
  id: '/cuidados',
  path: '/cuidados',
  getParentRoute: () => AuraRoute,
} as any)
const AuraCorpoRoute = AuraCorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => AuraRoute,
} as any)
const AuraCabeloRoute = AuraCabeloRouteImport.update({
  id: '/cabelo',
  path: '/cabelo',
  getParentRoute: () => AuraRoute,
} as any)
const AuraBarbaRoute = AuraBarbaRouteImport.update({
  id: '/barba',
  path: '/barba',
  getParentRoute: () => AuraRoute,
} as any)
const AuraAcessoriosRoute = AuraAcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => AuraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aura': typeof AuraRouteWithChildren
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/habitos': typeof HabitosRoute
  '/libertacao': typeof LibertacaoRoute
  '/aura/acessorios': typeof AuraAcessoriosRoute
  '/aura/barba': typeof AuraBarbaRoute
  '/aura/cabelo': typeof AuraCabeloRoute
  '/aura/corpo': typeof AuraCorpoRoute
  '/aura/cuidados': typeof AuraCuidadosRoute
  '/aura/perfume': typeof AuraPerfumeRoute
  '/aura/skincare': typeof AuraSkincareRoute
  '/aura/vestuario': typeof AuraVestuarioRoute
  '/aura/': typeof AuraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/habitos': typeof HabitosRoute
  '/libertacao': typeof LibertacaoRoute
  '/aura/acessorios': typeof AuraAcessoriosRoute
  '/aura/barba': typeof AuraBarbaRoute
  '/aura/cabelo': typeof AuraCabeloRoute
  '/aura/corpo': typeof AuraCorpoRoute
  '/aura/cuidados': typeof AuraCuidadosRoute
  '/aura/perfume': typeof AuraPerfumeRoute
  '/aura/skincare': typeof AuraSkincareRoute
  '/aura/vestuario': typeof AuraVestuarioRoute
  '/aura': typeof AuraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aura': typeof AuraRouteWithChildren
  '/biblioteca': typeof BibliotecaRoute
  '/dashboard': typeof DashboardRoute
  '/habitos': typeof HabitosRoute
  '/libertacao': typeof LibertacaoRoute
  '/aura/acessorios': typeof AuraAcessoriosRoute
  '/aura/barba': typeof AuraBarbaRoute
  '/aura/cabelo': typeof AuraCabeloRoute
  '/aura/corpo': typeof AuraCorpoRoute
  '/aura/cuidados': typeof AuraCuidadosRoute
  '/aura/perfume': typeof AuraPerfumeRoute
  '/aura/skincare': typeof AuraSkincareRoute
  '/aura/vestuario': typeof AuraVestuarioRoute
  '/aura/': typeof AuraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aura'
    | '/biblioteca'
    | '/dashboard'
    | '/habitos'
    | '/libertacao'
    | '/aura/acessorios'
    | '/aura/barba'
    | '/aura/cabelo'
    | '/aura/corpo'
    | '/aura/cuidados'
    | '/aura/perfume'
    | '/aura/skincare'
    | '/aura/vestuario'
    | '/aura/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/dashboard'
    | '/habitos'
    | '/libertacao'
    | '/aura/acessorios'
    | '/aura/barba'
    | '/aura/cabelo'
    | '/aura/corpo'
    | '/aura/cuidados'
    | '/aura/perfume'
    | '/aura/skincare'
    | '/aura/vestuario'
    | '/aura'
  id:
    | '__root__'
    | '/'
    | '/aura'
    | '/biblioteca'
    | '/dashboard'
    | '/habitos'
    | '/libertacao'
    | '/aura/acessorios'
    | '/aura/barba'
    | '/aura/cabelo'
    | '/aura/corpo'
    | '/aura/cuidados'
    | '/aura/perfume'
    | '/aura/skincare'
    | '/aura/vestuario'
    | '/aura/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuraRoute: typeof AuraRouteWithChildren
  BibliotecaRoute: typeof BibliotecaRoute
  DashboardRoute: typeof DashboardRoute
  HabitosRoute: typeof HabitosRoute
  LibertacaoRoute: typeof LibertacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/libertacao': {
      id: '/libertacao'
      path: '/libertacao'
      fullPath: '/libertacao'
      preLoaderRoute: typeof LibertacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura': {
      id: '/aura'
      path: '/aura'
      fullPath: '/aura'
      preLoaderRoute: typeof AuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aura/': {
      id: '/aura/'
      path: '/'
      fullPath: '/aura/'
      preLoaderRoute: typeof AuraIndexRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/vestuario': {
      id: '/aura/vestuario'
      path: '/vestuario'
      fullPath: '/aura/vestuario'
      preLoaderRoute: typeof AuraVestuarioRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/skincare': {
      id: '/aura/skincare'
      path: '/skincare'
      fullPath: '/aura/skincare'
      preLoaderRoute: typeof AuraSkincareRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/perfume': {
      id: '/aura/perfume'
      path: '/perfume'
      fullPath: '/aura/perfume'
      preLoaderRoute: typeof AuraPerfumeRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/cuidados': {
      id: '/aura/cuidados'
      path: '/cuidados'
      fullPath: '/aura/cuidados'
      preLoaderRoute: typeof AuraCuidadosRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/corpo': {
      id: '/aura/corpo'
      path: '/corpo'
      fullPath: '/aura/corpo'
      preLoaderRoute: typeof AuraCorpoRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/cabelo': {
      id: '/aura/cabelo'
      path: '/cabelo'
      fullPath: '/aura/cabelo'
      preLoaderRoute: typeof AuraCabeloRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/barba': {
      id: '/aura/barba'
      path: '/barba'
      fullPath: '/aura/barba'
      preLoaderRoute: typeof AuraBarbaRouteImport
      parentRoute: typeof AuraRoute
    }
    '/aura/acessorios': {
      id: '/aura/acessorios'
      path: '/acessorios'
      fullPath: '/aura/acessorios'
      preLoaderRoute: typeof AuraAcessoriosRouteImport
      parentRoute: typeof AuraRoute
    }
  }
}

interface AuraRouteChildren {
  AuraAcessoriosRoute: typeof AuraAcessoriosRoute
  AuraBarbaRoute: typeof AuraBarbaRoute
  AuraCabeloRoute: typeof AuraCabeloRoute
  AuraCorpoRoute: typeof AuraCorpoRoute
  AuraCuidadosRoute: typeof AuraCuidadosRoute
  AuraPerfumeRoute: typeof AuraPerfumeRoute
  AuraSkincareRoute: typeof AuraSkincareRoute
  AuraVestuarioRoute: typeof AuraVestuarioRoute
  AuraIndexRoute: typeof AuraIndexRoute
}

const AuraRouteChildren: AuraRouteChildren = {
  AuraAcessoriosRoute: AuraAcessoriosRoute,
  AuraBarbaRoute: AuraBarbaRoute,
  AuraCabeloRoute: AuraCabeloRoute,
  AuraCorpoRoute: AuraCorpoRoute,
  AuraCuidadosRoute: AuraCuidadosRoute,
  AuraPerfumeRoute: AuraPerfumeRoute,
  AuraSkincareRoute: AuraSkincareRoute,
  AuraVestuarioRoute: AuraVestuarioRoute,
  AuraIndexRoute: AuraIndexRoute,
}

const AuraRouteWithChildren = AuraRoute._addFileChildren(AuraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuraRoute: AuraRouteWithChildren,
  BibliotecaRoute: BibliotecaRoute,
  DashboardRoute: DashboardRoute,
  HabitosRoute: HabitosRoute,
  LibertacaoRoute: LibertacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
